project:
  type: website
  output-dir: docs  # <-- FONDAMENTALE per GitHub Pages semplice

website:
  title: "My personal site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    number-sections: true

navbar:
  left:
    - text: Home
      href: index.qmd
    - text: Projects
      href: projects/index.qmd
    - text: Blog
      href: posts/index.qmd
    - text: About
      href: about.qmd

page:
  toc: true
  toc-depth: 2