project:
  type: website
  output-dir: docs  
  resources: "*.png"

website:
  title: "Kiize's personal page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Projects
      - href: gists/index.qmd
        text: Gists

format:
  html:
    theme:
      light: morph
      dark: [vapor, theme-dark.scss]
    number-sections: false
    respect-user-color-scheme: true

page:
  toc: true
  toc-depth: 2